### ISSUE TITLE
When expanding the snippets, inserts an `i`

### ISSUE THREAD

**Issue by baldore** [fhill2/telescope-ultisnips.nvim#1]
Hey, what's up? First at all, great plugin. I was wondering why this happens when I run the command.

![image](https://user-images.githubusercontent.com/3131037/110469361-6699d100-808e-11eb-9e58-2e149a2e1a32.png)

I see that in the code you have this:

https://github.com/fhill2/telescope-ultisnips.nvim/blob/main/lua/telescope/_extensions/ultisnips.lua#L106

Is that something actually required?

**Comment by fhill2** [comment]
Hi baldore, glad you like it!

Fixed.
Thank you for pointing this out, `nvim_feedkeys` had no use after snippet insertion.
