### ISSUE TITLE
how to install with Packer?

### ISSUE THREAD

**Issue by jojoyuji** [fhill2/telescope-ultisnips.nvim#2]
Hi! I'm having some trouble on installing with packer.
I tried:

```
  use {
    'fhill2/telescope-ultisnips.nvim',
    setup = function()
      require'telescope'.load_extension('ultisnips')
     end
  }
```
But it gives me an error when running `:Telescope ultisnips ultisnips` :

```This extension doesn't exist or is not installed: ultisnips ```

am I doing something wrong?

**Comment by fhill2** [comment]
Hi @jojoyuji 
Is `telescope-ultisnips.nvim` the only extension that can't be loaded in this way?

I have had trouble loading Telescope extensions like this in the past too. 

My solution was to manually execute packadd after packer.nvim init() function:

```lua

-- packer init function
use 'nvim-telescope/telescope.nvim'

use {
    'fhill2/telescope-ultisnips.nvim',
    config = function()
      require'telescope'.load_extension('ultisnips')
     end
  }

-- outside/after packer init function in init.lua

vim.api.nvim_command('packadd telescope-ultisnips.nvim')

```
Let me know if the above works for you.

**Comment by jojoyuji** [comment]
Hi @fhill2, thx for the quick response!

Oh I see! I was missing the 
```lua
vim.api.nvim_command('packadd telescope-ultisnips.nvim')
```

It think it actually solved the previous issue I had:
```
This extension doesn't exist or is not installed: ultisnips
```
but I think I got another error: 

When I run 
```
:Telescope ultisnips ultisnips
``` 
I got this error:
```
E5108: Error executing lua Vim:E117: Unknown function: UltiSnips#SnippetsInCurrentScope
```
Any tips?  😬 


BTW I'm using the frecency telescope extension, it is set like this:

```lua
  use {
    'nvim-telescope/telescope-frecency.nvim',
    requires = {'tami5/sql.nvim'},
    config = function() require'telescope'.load_extension('frecency') end
  }
```

( I also changed `setup` to `config` like you mentioned)

The  frecency extention is working well AFAIK, I did not know you had to call 
```lua
vim.api.nvim_command('packadd telescope-ultisnips.nvim')
```

**Comment by fhill2** [comment]
Great that it worked!!
That error is because nvim can't find Ultisnips. I should set that errmsg to be something more meaningful.
Install [ultisnips](https://github.com/SirVer/ultisnips) and you should be all set.

**Comment by jojoyuji** [comment]
omg I'm so dumb, I was using `coc` to expand my ultisnips snippets without using ultisnips, so I did not have UltiSnips installed 🤦 

It worked like a charm! tysm!
