### ISSUE TITLE
Breaks with snippets containing literal CR

### ISSUE THREAD

**Issue by amenonsen** [fhill2/telescope-ultisnips.nvim#5]
I have the following snippet defined:

```
snippet at "Link to selected text"
<a href="$1">${VISUAL:/[ ^@^M]*$//}</a>
endsnippet
```

The ^@ and ^M above are actually literal NUL and CR characters respectively in the snippet definition.

While scrolling through the Telescope popup of my snippets, when I reach the above snippet, I get an error that says "error executing lua […filename…] string cannot contain newline" in the statusline below (it's gone too quickly for me to read the whole thing). Then I can no longer scroll between the snippet names, my cursor is in the preview window to the right (and I can type there!), and nothing else works, I have to hit Esc and :q out of the popup.

I've removed the ^@^M from my snippet, and your plugin works fine now, but I thought I'd report this behaviour anyway.

Thanks for a very useful plugin!

**Comment by fhill2** [comment]
Hey @amenonsen. You are welcome!
Thank you for finding & reporting this. Very strange behaviour indeed.

I'm having a hard time reproducing this on my end. When trying to reproduce, this snippet doesn't error out the Telescope picker when I hover over it.

If I recall, this type of error is produced by `nvim_buf_set_lines()` when trying to write to a buffer strings that contain newlines. I'm guessing it's erroring out in telescope/pickers.lua when Telescope writes to the picker or previewer UI buffer, something upstream.

When you say `error executing lua [..filename..]` - which file is this?

**Comment by amenonsen** [comment]
I managed to reproduce the problem with a clean neovim config that just uses packer to load UltiSnips, Telescope, and your plugin, with no other config except for the snippets file containing that one snippet. You're right about the error being from nvim_buf_set_lines(), here is the error message I see below the status line:

```
E5108: Error executing lua ...e-ultisnips.nvim/lua/telescope/_extensions/ultisnips.lua:88: String cannot contain newlines
```

Although the error _says_ "cannot contain newlines", the problem is really the literal NUL character. Without that, the problem doesn't happen. With it, you don't need $VISUAL or anything, even a snippet with just a lone `^@` breaks the same way.

On the basis that the problem may be upstream somewhere, and because I can't even remember why I put in that NUL in the first place, I'm going to close this issue now. Thanks for looking into it.
